In [ ]:
1. Write a Python Program to find sum of array?

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [4]:
a=np.array(l)

In [8]:
sum(a)

21

In [ ]:
2. Write a Python Program to find largest element in an array?

In [10]:
a

array([1, 2, 3, 4, 5, 6])

In [11]:
max(a)

6

In [ ]:
3. Write a Python Program for array rotation?

In [44]:
a

array([1, 2, 3, 4, 5, 6])

In [45]:
a.T

array([1, 2, 3, 4, 5, 6])

In [ ]:
4. Write a Python Program to Split the array and add the first part to the end?

In [20]:
a

array([1, 2, 3, 4, 5, 6])

In [29]:
b=np.array_split(a,6)

In [31]:
b

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

In [ ]:
5. Write a Python Program to check if given array is Monotonic?

In [41]:
def isMonotonic(A): 
        a,b=0,0 
        for i in range(len(A)-1): 
            if A[i+1]>A[i]: 
                a+=1 
            elif A[i+1]<A[i]: 
                b+=1 
        if 0 in [a,b]: 
            return True 
        else: 
            return False 

In [43]:
isMonotonic(np.array([1,2,3,1,5]))

False