In [ ]:
1. Write a Python Program to Add Two Matrices?

In [5]:
import numpy as np
mat1 = np.array([[1,6,4],
        [4,5,6],
        [7,6,9]])

mat2 = np.array([[2,5,4],
        [5,8,7],
        [8,3,1]])
s=np.add(mat1,mat2)
print(s)

[[ 3 11  8]
 [ 9 13 13]
 [15  9 10]]


In [ ]:
Write a Python Program to Multiply Two Matrices?


In [7]:
m=mat1@mat2
m

array([[ 64,  65,  50],
       [ 81,  78,  57],
       [116, 110,  79]])

In [ ]:
Write a Python Program to Transpose a Matrix?

In [8]:
mat1

array([[1, 6, 4],
       [4, 5, 6],
       [7, 6, 9]])

In [9]:
mat1.T

array([[1, 4, 7],
       [6, 5, 6],
       [4, 6, 9]])

In [ ]:
Write a Python Program to Sort Words in Alphabetic Order?


In [10]:
str = input("Enter some string: ")

words = str.split()
words.sort()
for word in words:
    print(word)

Enter some string: my name is siddalinga patil
is
my
name
patil
siddalinga


In [ ]:
Write a Python Program to Remove Punctuation From a String?


In [12]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter some string with panctuations")
no_punct = ""
for i in str:
    if i not in punctuations:
        no_punct = no_punct + i
        
print(no_punct)

Enter some string with panctuationssidda patiol $#!bgy
sidda patiol bgy
